### ISSUE TITLE
Can't install on node v0.10.15

### ISSUE THREAD

**Issue by blackrabbit99** [smartcomments/smartcomments#25]
npm ERR! System Darwin 13.0.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "-g" "smartcomments"
npm ERR! cwd /Users/blackrabbit99/Sites/picsio-dev/picsio/src
npm ERR! node -v v0.10.15
npm ERR! npm -v 1.3.5
npm ERR! code EPEERINVALID

**Comment by darielnoel** [comment]
Hello Mr. Zakharchenko, thank you very much for sharing with us the problem. Unfortunately we do not have a Mac to test the scenario that mistake. We would be very grateful if you can help us solve it. We tested this test scenario:

node-v v0.10.15
npm-v 1.3.5

  In Debian, Ubuntu and Windows and works well.

Try to do the following:

1 - Try to install some other NPM module. For example npm install-g grunt.

2 - Try to run the install command in SuperUser mode.

If the same error persists please send us the file npm-debug.log 

Best regards.

**Comment by blackrabbit99** [comment]
Resolved by uninstalling bower.

**Comment by darielnoel** [comment]
We are very happy that you were able to solve the problem. 

Regards.
