### ISSUE TITLE
Running smartcomments as a grunt task

### ISSUE THREAD

**Issue by marcel0ll** [smartcomments/smartcomments#35]
Is it possible to run smartcomments as a grunt task?

**Comment by shouse** [comment]
I'd guess that you could do it via Grunt Shell - https://github.com/sindresorhus/grunt-shell
Post back if you try that and it works.

**Comment by ptitgraig** [comment]
Tried and it worked

```
npm install --save-dev smartcomments
npm install --save-dev grunt-shell
```

In Gruntfile.js:

```
shell: {
  smartcomments: {
    command: 'node ./node_modules/smartcomments/bin/smartcomments --generate -t ./your_app_path'
  }
 },
```

```
 grunt.task.run([
  'shell:smartcomments',
]);
```

**Comment by goldtreefrog** [comment]
I only mention this for new visitors to this thread.  Somehow I managed to install smartcomments globally rather than locally, but once I figured out the actual path to it, it worked as shown previously, even now, in 2018. 

Thanks!
